CREATE TABLE IF NOT EXISTS logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    level VARCHAR(32) NOT NULL,
    server VARCHAR(255),
    source VARCHAR(255),
    ip_address VARCHAR(255),
    message VARCHAR(255),
    endpoint VARCHAR(255),
    http_method VARCHAR(255),
    http_status INTEGER,
    request_id VARCHAR(255),
    environment VARCHAR(255),
    severity VARCHAR(255),
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON logs (timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_level ON logs (level);
CREATE INDEX IF NOT EXISTS idx_logs_server ON logs (server);
CREATE INDEX IF NOT EXISTS idx_logs_source ON logs (source);
CREATE INDEX IF NOT EXISTS idx_logs_ip_address ON logs (ip_address);
CREATE INDEX IF NOT EXISTS idx_logs_severity ON logs (severity);
